// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: env.proto

public final class EnvironmentMonitoringProtos {
  private EnvironmentMonitoringProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface EnvironmentUpdateOrBuilder extends
      // @@protoc_insertion_point(interface_extends:EnvironmentUpdate)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .EnvironmentUpdate.SensorRecord sensor_record = 1;</code>
     */
    java.util.List<EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecord> 
        getSensorRecordList();
    /**
     * <code>repeated .EnvironmentUpdate.SensorRecord sensor_record = 1;</code>
     */
    EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecord getSensorRecord(int index);
    /**
     * <code>repeated .EnvironmentUpdate.SensorRecord sensor_record = 1;</code>
     */
    int getSensorRecordCount();
    /**
     * <code>repeated .EnvironmentUpdate.SensorRecord sensor_record = 1;</code>
     */
    java.util.List<? extends EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecordOrBuilder> 
        getSensorRecordOrBuilderList();
    /**
     * <code>repeated .EnvironmentUpdate.SensorRecord sensor_record = 1;</code>
     */
    EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecordOrBuilder getSensorRecordOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code EnvironmentUpdate}
   */
  public static final class EnvironmentUpdate extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:EnvironmentUpdate)
      EnvironmentUpdateOrBuilder {
    // Use EnvironmentUpdate.newBuilder() to construct.
    private EnvironmentUpdate(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private EnvironmentUpdate(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final EnvironmentUpdate defaultInstance;
    public static EnvironmentUpdate getDefaultInstance() {
      return defaultInstance;
    }

    public EnvironmentUpdate getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private EnvironmentUpdate(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                sensorRecord_ = new java.util.ArrayList<EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecord>();
                mutable_bitField0_ |= 0x00000001;
              }
              sensorRecord_.add(input.readMessage(EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecord.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          sensorRecord_ = java.util.Collections.unmodifiableList(sensorRecord_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return EnvironmentMonitoringProtos.internal_static_EnvironmentUpdate_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return EnvironmentMonitoringProtos.internal_static_EnvironmentUpdate_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              EnvironmentMonitoringProtos.EnvironmentUpdate.class, EnvironmentMonitoringProtos.EnvironmentUpdate.Builder.class);
    }

    public static com.google.protobuf.Parser<EnvironmentUpdate> PARSER =
        new com.google.protobuf.AbstractParser<EnvironmentUpdate>() {
      public EnvironmentUpdate parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new EnvironmentUpdate(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<EnvironmentUpdate> getParserForType() {
      return PARSER;
    }

    public interface SensorDataOrBuilder extends
        // @@protoc_insertion_point(interface_extends:EnvironmentUpdate.SensorData)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>optional int32 key = 1;</code>
       */
      boolean hasKey();
      /**
       * <code>optional int32 key = 1;</code>
       */
      int getKey();

      /**
       * <code>optional float value = 2;</code>
       */
      boolean hasValue();
      /**
       * <code>optional float value = 2;</code>
       */
      float getValue();
    }
    /**
     * Protobuf type {@code EnvironmentUpdate.SensorData}
     */
    public static final class SensorData extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:EnvironmentUpdate.SensorData)
        SensorDataOrBuilder {
      // Use SensorData.newBuilder() to construct.
      private SensorData(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private SensorData(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final SensorData defaultInstance;
      public static SensorData getDefaultInstance() {
        return defaultInstance;
      }

      public SensorData getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private SensorData(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 8: {
                bitField0_ |= 0x00000001;
                key_ = input.readInt32();
                break;
              }
              case 21: {
                bitField0_ |= 0x00000002;
                value_ = input.readFloat();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return EnvironmentMonitoringProtos.internal_static_EnvironmentUpdate_SensorData_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return EnvironmentMonitoringProtos.internal_static_EnvironmentUpdate_SensorData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                EnvironmentMonitoringProtos.EnvironmentUpdate.SensorData.class, EnvironmentMonitoringProtos.EnvironmentUpdate.SensorData.Builder.class);
      }

      public static com.google.protobuf.Parser<SensorData> PARSER =
          new com.google.protobuf.AbstractParser<SensorData>() {
        public SensorData parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new SensorData(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<SensorData> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      public static final int KEY_FIELD_NUMBER = 1;
      private int key_;
      /**
       * <code>optional int32 key = 1;</code>
       */
      public boolean hasKey() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 key = 1;</code>
       */
      public int getKey() {
        return key_;
      }

      public static final int VALUE_FIELD_NUMBER = 2;
      private float value_;
      /**
       * <code>optional float value = 2;</code>
       */
      public boolean hasValue() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional float value = 2;</code>
       */
      public float getValue() {
        return value_;
      }

      private void initFields() {
        key_ = 0;
        value_ = 0F;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeInt32(1, key_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeFloat(2, value_);
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(1, key_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeFloatSize(2, value_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static EnvironmentMonitoringProtos.EnvironmentUpdate.SensorData parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static EnvironmentMonitoringProtos.EnvironmentUpdate.SensorData parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static EnvironmentMonitoringProtos.EnvironmentUpdate.SensorData parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static EnvironmentMonitoringProtos.EnvironmentUpdate.SensorData parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static EnvironmentMonitoringProtos.EnvironmentUpdate.SensorData parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static EnvironmentMonitoringProtos.EnvironmentUpdate.SensorData parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static EnvironmentMonitoringProtos.EnvironmentUpdate.SensorData parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static EnvironmentMonitoringProtos.EnvironmentUpdate.SensorData parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static EnvironmentMonitoringProtos.EnvironmentUpdate.SensorData parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static EnvironmentMonitoringProtos.EnvironmentUpdate.SensorData parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(EnvironmentMonitoringProtos.EnvironmentUpdate.SensorData prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code EnvironmentUpdate.SensorData}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:EnvironmentUpdate.SensorData)
          EnvironmentMonitoringProtos.EnvironmentUpdate.SensorDataOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return EnvironmentMonitoringProtos.internal_static_EnvironmentUpdate_SensorData_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return EnvironmentMonitoringProtos.internal_static_EnvironmentUpdate_SensorData_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  EnvironmentMonitoringProtos.EnvironmentUpdate.SensorData.class, EnvironmentMonitoringProtos.EnvironmentUpdate.SensorData.Builder.class);
        }

        // Construct using EnvironmentMonitoringProtos.EnvironmentUpdate.SensorData.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          key_ = 0;
          bitField0_ = (bitField0_ & ~0x00000001);
          value_ = 0F;
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return EnvironmentMonitoringProtos.internal_static_EnvironmentUpdate_SensorData_descriptor;
        }

        public EnvironmentMonitoringProtos.EnvironmentUpdate.SensorData getDefaultInstanceForType() {
          return EnvironmentMonitoringProtos.EnvironmentUpdate.SensorData.getDefaultInstance();
        }

        public EnvironmentMonitoringProtos.EnvironmentUpdate.SensorData build() {
          EnvironmentMonitoringProtos.EnvironmentUpdate.SensorData result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public EnvironmentMonitoringProtos.EnvironmentUpdate.SensorData buildPartial() {
          EnvironmentMonitoringProtos.EnvironmentUpdate.SensorData result = new EnvironmentMonitoringProtos.EnvironmentUpdate.SensorData(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.key_ = key_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.value_ = value_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof EnvironmentMonitoringProtos.EnvironmentUpdate.SensorData) {
            return mergeFrom((EnvironmentMonitoringProtos.EnvironmentUpdate.SensorData)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(EnvironmentMonitoringProtos.EnvironmentUpdate.SensorData other) {
          if (other == EnvironmentMonitoringProtos.EnvironmentUpdate.SensorData.getDefaultInstance()) return this;
          if (other.hasKey()) {
            setKey(other.getKey());
          }
          if (other.hasValue()) {
            setValue(other.getValue());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          EnvironmentMonitoringProtos.EnvironmentUpdate.SensorData parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (EnvironmentMonitoringProtos.EnvironmentUpdate.SensorData) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private int key_ ;
        /**
         * <code>optional int32 key = 1;</code>
         */
        public boolean hasKey() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>optional int32 key = 1;</code>
         */
        public int getKey() {
          return key_;
        }
        /**
         * <code>optional int32 key = 1;</code>
         */
        public Builder setKey(int value) {
          bitField0_ |= 0x00000001;
          key_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional int32 key = 1;</code>
         */
        public Builder clearKey() {
          bitField0_ = (bitField0_ & ~0x00000001);
          key_ = 0;
          onChanged();
          return this;
        }

        private float value_ ;
        /**
         * <code>optional float value = 2;</code>
         */
        public boolean hasValue() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>optional float value = 2;</code>
         */
        public float getValue() {
          return value_;
        }
        /**
         * <code>optional float value = 2;</code>
         */
        public Builder setValue(float value) {
          bitField0_ |= 0x00000002;
          value_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional float value = 2;</code>
         */
        public Builder clearValue() {
          bitField0_ = (bitField0_ & ~0x00000002);
          value_ = 0F;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:EnvironmentUpdate.SensorData)
      }

      static {
        defaultInstance = new SensorData(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:EnvironmentUpdate.SensorData)
    }

    public interface SensorRecordOrBuilder extends
        // @@protoc_insertion_point(interface_extends:EnvironmentUpdate.SensorRecord)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>optional double latitude = 1;</code>
       */
      boolean hasLatitude();
      /**
       * <code>optional double latitude = 1;</code>
       */
      double getLatitude();

      /**
       * <code>optional double longitude = 2;</code>
       */
      boolean hasLongitude();
      /**
       * <code>optional double longitude = 2;</code>
       */
      double getLongitude();

      /**
       * <code>optional int64 timestamp = 3;</code>
       */
      boolean hasTimestamp();
      /**
       * <code>optional int64 timestamp = 3;</code>
       */
      long getTimestamp();

      /**
       * <code>optional string car_id = 4;</code>
       */
      boolean hasCarId();
      /**
       * <code>optional string car_id = 4;</code>
       */
      java.lang.String getCarId();
      /**
       * <code>optional string car_id = 4;</code>
       */
      com.google.protobuf.ByteString
          getCarIdBytes();

      /**
       * <code>optional int32 sequence_number = 5;</code>
       */
      boolean hasSequenceNumber();
      /**
       * <code>optional int32 sequence_number = 5;</code>
       */
      int getSequenceNumber();

      /**
       * <code>repeated .EnvironmentUpdate.SensorData sensor_data = 6;</code>
       */
      java.util.List<EnvironmentMonitoringProtos.EnvironmentUpdate.SensorData> 
          getSensorDataList();
      /**
       * <code>repeated .EnvironmentUpdate.SensorData sensor_data = 6;</code>
       */
      EnvironmentMonitoringProtos.EnvironmentUpdate.SensorData getSensorData(int index);
      /**
       * <code>repeated .EnvironmentUpdate.SensorData sensor_data = 6;</code>
       */
      int getSensorDataCount();
      /**
       * <code>repeated .EnvironmentUpdate.SensorData sensor_data = 6;</code>
       */
      java.util.List<? extends EnvironmentMonitoringProtos.EnvironmentUpdate.SensorDataOrBuilder> 
          getSensorDataOrBuilderList();
      /**
       * <code>repeated .EnvironmentUpdate.SensorData sensor_data = 6;</code>
       */
      EnvironmentMonitoringProtos.EnvironmentUpdate.SensorDataOrBuilder getSensorDataOrBuilder(
          int index);
    }
    /**
     * Protobuf type {@code EnvironmentUpdate.SensorRecord}
     */
    public static final class SensorRecord extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:EnvironmentUpdate.SensorRecord)
        SensorRecordOrBuilder {
      // Use SensorRecord.newBuilder() to construct.
      private SensorRecord(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private SensorRecord(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final SensorRecord defaultInstance;
      public static SensorRecord getDefaultInstance() {
        return defaultInstance;
      }

      public SensorRecord getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private SensorRecord(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 9: {
                bitField0_ |= 0x00000001;
                latitude_ = input.readDouble();
                break;
              }
              case 17: {
                bitField0_ |= 0x00000002;
                longitude_ = input.readDouble();
                break;
              }
              case 24: {
                bitField0_ |= 0x00000004;
                timestamp_ = input.readInt64();
                break;
              }
              case 34: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000008;
                carId_ = bs;
                break;
              }
              case 40: {
                bitField0_ |= 0x00000010;
                sequenceNumber_ = input.readInt32();
                break;
              }
              case 50: {
                if (!((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
                  sensorData_ = new java.util.ArrayList<EnvironmentMonitoringProtos.EnvironmentUpdate.SensorData>();
                  mutable_bitField0_ |= 0x00000020;
                }
                sensorData_.add(input.readMessage(EnvironmentMonitoringProtos.EnvironmentUpdate.SensorData.PARSER, extensionRegistry));
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          if (((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
            sensorData_ = java.util.Collections.unmodifiableList(sensorData_);
          }
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return EnvironmentMonitoringProtos.internal_static_EnvironmentUpdate_SensorRecord_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return EnvironmentMonitoringProtos.internal_static_EnvironmentUpdate_SensorRecord_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecord.class, EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecord.Builder.class);
      }

      public static com.google.protobuf.Parser<SensorRecord> PARSER =
          new com.google.protobuf.AbstractParser<SensorRecord>() {
        public SensorRecord parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new SensorRecord(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<SensorRecord> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      public static final int LATITUDE_FIELD_NUMBER = 1;
      private double latitude_;
      /**
       * <code>optional double latitude = 1;</code>
       */
      public boolean hasLatitude() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional double latitude = 1;</code>
       */
      public double getLatitude() {
        return latitude_;
      }

      public static final int LONGITUDE_FIELD_NUMBER = 2;
      private double longitude_;
      /**
       * <code>optional double longitude = 2;</code>
       */
      public boolean hasLongitude() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional double longitude = 2;</code>
       */
      public double getLongitude() {
        return longitude_;
      }

      public static final int TIMESTAMP_FIELD_NUMBER = 3;
      private long timestamp_;
      /**
       * <code>optional int64 timestamp = 3;</code>
       */
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int64 timestamp = 3;</code>
       */
      public long getTimestamp() {
        return timestamp_;
      }

      public static final int CAR_ID_FIELD_NUMBER = 4;
      private java.lang.Object carId_;
      /**
       * <code>optional string car_id = 4;</code>
       */
      public boolean hasCarId() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string car_id = 4;</code>
       */
      public java.lang.String getCarId() {
        java.lang.Object ref = carId_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            carId_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string car_id = 4;</code>
       */
      public com.google.protobuf.ByteString
          getCarIdBytes() {
        java.lang.Object ref = carId_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          carId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int SEQUENCE_NUMBER_FIELD_NUMBER = 5;
      private int sequenceNumber_;
      /**
       * <code>optional int32 sequence_number = 5;</code>
       */
      public boolean hasSequenceNumber() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int32 sequence_number = 5;</code>
       */
      public int getSequenceNumber() {
        return sequenceNumber_;
      }

      public static final int SENSOR_DATA_FIELD_NUMBER = 6;
      private java.util.List<EnvironmentMonitoringProtos.EnvironmentUpdate.SensorData> sensorData_;
      /**
       * <code>repeated .EnvironmentUpdate.SensorData sensor_data = 6;</code>
       */
      public java.util.List<EnvironmentMonitoringProtos.EnvironmentUpdate.SensorData> getSensorDataList() {
        return sensorData_;
      }
      /**
       * <code>repeated .EnvironmentUpdate.SensorData sensor_data = 6;</code>
       */
      public java.util.List<? extends EnvironmentMonitoringProtos.EnvironmentUpdate.SensorDataOrBuilder> 
          getSensorDataOrBuilderList() {
        return sensorData_;
      }
      /**
       * <code>repeated .EnvironmentUpdate.SensorData sensor_data = 6;</code>
       */
      public int getSensorDataCount() {
        return sensorData_.size();
      }
      /**
       * <code>repeated .EnvironmentUpdate.SensorData sensor_data = 6;</code>
       */
      public EnvironmentMonitoringProtos.EnvironmentUpdate.SensorData getSensorData(int index) {
        return sensorData_.get(index);
      }
      /**
       * <code>repeated .EnvironmentUpdate.SensorData sensor_data = 6;</code>
       */
      public EnvironmentMonitoringProtos.EnvironmentUpdate.SensorDataOrBuilder getSensorDataOrBuilder(
          int index) {
        return sensorData_.get(index);
      }

      private void initFields() {
        latitude_ = 0D;
        longitude_ = 0D;
        timestamp_ = 0L;
        carId_ = "";
        sequenceNumber_ = 0;
        sensorData_ = java.util.Collections.emptyList();
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeDouble(1, latitude_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeDouble(2, longitude_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          output.writeInt64(3, timestamp_);
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          output.writeBytes(4, getCarIdBytes());
        }
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          output.writeInt32(5, sequenceNumber_);
        }
        for (int i = 0; i < sensorData_.size(); i++) {
          output.writeMessage(6, sensorData_.get(i));
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeDoubleSize(1, latitude_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeDoubleSize(2, longitude_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt64Size(3, timestamp_);
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(4, getCarIdBytes());
        }
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(5, sequenceNumber_);
        }
        for (int i = 0; i < sensorData_.size(); i++) {
          size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(6, sensorData_.get(i));
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecord parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecord parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecord parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecord parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecord parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecord parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecord parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecord parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecord parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecord parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecord prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code EnvironmentUpdate.SensorRecord}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:EnvironmentUpdate.SensorRecord)
          EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecordOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return EnvironmentMonitoringProtos.internal_static_EnvironmentUpdate_SensorRecord_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return EnvironmentMonitoringProtos.internal_static_EnvironmentUpdate_SensorRecord_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecord.class, EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecord.Builder.class);
        }

        // Construct using EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecord.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
            getSensorDataFieldBuilder();
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          latitude_ = 0D;
          bitField0_ = (bitField0_ & ~0x00000001);
          longitude_ = 0D;
          bitField0_ = (bitField0_ & ~0x00000002);
          timestamp_ = 0L;
          bitField0_ = (bitField0_ & ~0x00000004);
          carId_ = "";
          bitField0_ = (bitField0_ & ~0x00000008);
          sequenceNumber_ = 0;
          bitField0_ = (bitField0_ & ~0x00000010);
          if (sensorDataBuilder_ == null) {
            sensorData_ = java.util.Collections.emptyList();
            bitField0_ = (bitField0_ & ~0x00000020);
          } else {
            sensorDataBuilder_.clear();
          }
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return EnvironmentMonitoringProtos.internal_static_EnvironmentUpdate_SensorRecord_descriptor;
        }

        public EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecord getDefaultInstanceForType() {
          return EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecord.getDefaultInstance();
        }

        public EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecord build() {
          EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecord result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecord buildPartial() {
          EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecord result = new EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecord(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.latitude_ = latitude_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.longitude_ = longitude_;
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000004;
          }
          result.timestamp_ = timestamp_;
          if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
            to_bitField0_ |= 0x00000008;
          }
          result.carId_ = carId_;
          if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
            to_bitField0_ |= 0x00000010;
          }
          result.sequenceNumber_ = sequenceNumber_;
          if (sensorDataBuilder_ == null) {
            if (((bitField0_ & 0x00000020) == 0x00000020)) {
              sensorData_ = java.util.Collections.unmodifiableList(sensorData_);
              bitField0_ = (bitField0_ & ~0x00000020);
            }
            result.sensorData_ = sensorData_;
          } else {
            result.sensorData_ = sensorDataBuilder_.build();
          }
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecord) {
            return mergeFrom((EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecord)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecord other) {
          if (other == EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecord.getDefaultInstance()) return this;
          if (other.hasLatitude()) {
            setLatitude(other.getLatitude());
          }
          if (other.hasLongitude()) {
            setLongitude(other.getLongitude());
          }
          if (other.hasTimestamp()) {
            setTimestamp(other.getTimestamp());
          }
          if (other.hasCarId()) {
            bitField0_ |= 0x00000008;
            carId_ = other.carId_;
            onChanged();
          }
          if (other.hasSequenceNumber()) {
            setSequenceNumber(other.getSequenceNumber());
          }
          if (sensorDataBuilder_ == null) {
            if (!other.sensorData_.isEmpty()) {
              if (sensorData_.isEmpty()) {
                sensorData_ = other.sensorData_;
                bitField0_ = (bitField0_ & ~0x00000020);
              } else {
                ensureSensorDataIsMutable();
                sensorData_.addAll(other.sensorData_);
              }
              onChanged();
            }
          } else {
            if (!other.sensorData_.isEmpty()) {
              if (sensorDataBuilder_.isEmpty()) {
                sensorDataBuilder_.dispose();
                sensorDataBuilder_ = null;
                sensorData_ = other.sensorData_;
                bitField0_ = (bitField0_ & ~0x00000020);
                sensorDataBuilder_ = 
                  com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                     getSensorDataFieldBuilder() : null;
              } else {
                sensorDataBuilder_.addAllMessages(other.sensorData_);
              }
            }
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecord parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecord) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private double latitude_ ;
        /**
         * <code>optional double latitude = 1;</code>
         */
        public boolean hasLatitude() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>optional double latitude = 1;</code>
         */
        public double getLatitude() {
          return latitude_;
        }
        /**
         * <code>optional double latitude = 1;</code>
         */
        public Builder setLatitude(double value) {
          bitField0_ |= 0x00000001;
          latitude_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional double latitude = 1;</code>
         */
        public Builder clearLatitude() {
          bitField0_ = (bitField0_ & ~0x00000001);
          latitude_ = 0D;
          onChanged();
          return this;
        }

        private double longitude_ ;
        /**
         * <code>optional double longitude = 2;</code>
         */
        public boolean hasLongitude() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>optional double longitude = 2;</code>
         */
        public double getLongitude() {
          return longitude_;
        }
        /**
         * <code>optional double longitude = 2;</code>
         */
        public Builder setLongitude(double value) {
          bitField0_ |= 0x00000002;
          longitude_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional double longitude = 2;</code>
         */
        public Builder clearLongitude() {
          bitField0_ = (bitField0_ & ~0x00000002);
          longitude_ = 0D;
          onChanged();
          return this;
        }

        private long timestamp_ ;
        /**
         * <code>optional int64 timestamp = 3;</code>
         */
        public boolean hasTimestamp() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        /**
         * <code>optional int64 timestamp = 3;</code>
         */
        public long getTimestamp() {
          return timestamp_;
        }
        /**
         * <code>optional int64 timestamp = 3;</code>
         */
        public Builder setTimestamp(long value) {
          bitField0_ |= 0x00000004;
          timestamp_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional int64 timestamp = 3;</code>
         */
        public Builder clearTimestamp() {
          bitField0_ = (bitField0_ & ~0x00000004);
          timestamp_ = 0L;
          onChanged();
          return this;
        }

        private java.lang.Object carId_ = "";
        /**
         * <code>optional string car_id = 4;</code>
         */
        public boolean hasCarId() {
          return ((bitField0_ & 0x00000008) == 0x00000008);
        }
        /**
         * <code>optional string car_id = 4;</code>
         */
        public java.lang.String getCarId() {
          java.lang.Object ref = carId_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              carId_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string car_id = 4;</code>
         */
        public com.google.protobuf.ByteString
            getCarIdBytes() {
          java.lang.Object ref = carId_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            carId_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string car_id = 4;</code>
         */
        public Builder setCarId(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
          carId_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string car_id = 4;</code>
         */
        public Builder clearCarId() {
          bitField0_ = (bitField0_ & ~0x00000008);
          carId_ = getDefaultInstance().getCarId();
          onChanged();
          return this;
        }
        /**
         * <code>optional string car_id = 4;</code>
         */
        public Builder setCarIdBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
          carId_ = value;
          onChanged();
          return this;
        }

        private int sequenceNumber_ ;
        /**
         * <code>optional int32 sequence_number = 5;</code>
         */
        public boolean hasSequenceNumber() {
          return ((bitField0_ & 0x00000010) == 0x00000010);
        }
        /**
         * <code>optional int32 sequence_number = 5;</code>
         */
        public int getSequenceNumber() {
          return sequenceNumber_;
        }
        /**
         * <code>optional int32 sequence_number = 5;</code>
         */
        public Builder setSequenceNumber(int value) {
          bitField0_ |= 0x00000010;
          sequenceNumber_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional int32 sequence_number = 5;</code>
         */
        public Builder clearSequenceNumber() {
          bitField0_ = (bitField0_ & ~0x00000010);
          sequenceNumber_ = 0;
          onChanged();
          return this;
        }

        private java.util.List<EnvironmentMonitoringProtos.EnvironmentUpdate.SensorData> sensorData_ =
          java.util.Collections.emptyList();
        private void ensureSensorDataIsMutable() {
          if (!((bitField0_ & 0x00000020) == 0x00000020)) {
            sensorData_ = new java.util.ArrayList<EnvironmentMonitoringProtos.EnvironmentUpdate.SensorData>(sensorData_);
            bitField0_ |= 0x00000020;
           }
        }

        private com.google.protobuf.RepeatedFieldBuilder<
            EnvironmentMonitoringProtos.EnvironmentUpdate.SensorData, EnvironmentMonitoringProtos.EnvironmentUpdate.SensorData.Builder, EnvironmentMonitoringProtos.EnvironmentUpdate.SensorDataOrBuilder> sensorDataBuilder_;

        /**
         * <code>repeated .EnvironmentUpdate.SensorData sensor_data = 6;</code>
         */
        public java.util.List<EnvironmentMonitoringProtos.EnvironmentUpdate.SensorData> getSensorDataList() {
          if (sensorDataBuilder_ == null) {
            return java.util.Collections.unmodifiableList(sensorData_);
          } else {
            return sensorDataBuilder_.getMessageList();
          }
        }
        /**
         * <code>repeated .EnvironmentUpdate.SensorData sensor_data = 6;</code>
         */
        public int getSensorDataCount() {
          if (sensorDataBuilder_ == null) {
            return sensorData_.size();
          } else {
            return sensorDataBuilder_.getCount();
          }
        }
        /**
         * <code>repeated .EnvironmentUpdate.SensorData sensor_data = 6;</code>
         */
        public EnvironmentMonitoringProtos.EnvironmentUpdate.SensorData getSensorData(int index) {
          if (sensorDataBuilder_ == null) {
            return sensorData_.get(index);
          } else {
            return sensorDataBuilder_.getMessage(index);
          }
        }
        /**
         * <code>repeated .EnvironmentUpdate.SensorData sensor_data = 6;</code>
         */
        public Builder setSensorData(
            int index, EnvironmentMonitoringProtos.EnvironmentUpdate.SensorData value) {
          if (sensorDataBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            ensureSensorDataIsMutable();
            sensorData_.set(index, value);
            onChanged();
          } else {
            sensorDataBuilder_.setMessage(index, value);
          }
          return this;
        }
        /**
         * <code>repeated .EnvironmentUpdate.SensorData sensor_data = 6;</code>
         */
        public Builder setSensorData(
            int index, EnvironmentMonitoringProtos.EnvironmentUpdate.SensorData.Builder builderForValue) {
          if (sensorDataBuilder_ == null) {
            ensureSensorDataIsMutable();
            sensorData_.set(index, builderForValue.build());
            onChanged();
          } else {
            sensorDataBuilder_.setMessage(index, builderForValue.build());
          }
          return this;
        }
        /**
         * <code>repeated .EnvironmentUpdate.SensorData sensor_data = 6;</code>
         */
        public Builder addSensorData(EnvironmentMonitoringProtos.EnvironmentUpdate.SensorData value) {
          if (sensorDataBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            ensureSensorDataIsMutable();
            sensorData_.add(value);
            onChanged();
          } else {
            sensorDataBuilder_.addMessage(value);
          }
          return this;
        }
        /**
         * <code>repeated .EnvironmentUpdate.SensorData sensor_data = 6;</code>
         */
        public Builder addSensorData(
            int index, EnvironmentMonitoringProtos.EnvironmentUpdate.SensorData value) {
          if (sensorDataBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            ensureSensorDataIsMutable();
            sensorData_.add(index, value);
            onChanged();
          } else {
            sensorDataBuilder_.addMessage(index, value);
          }
          return this;
        }
        /**
         * <code>repeated .EnvironmentUpdate.SensorData sensor_data = 6;</code>
         */
        public Builder addSensorData(
            EnvironmentMonitoringProtos.EnvironmentUpdate.SensorData.Builder builderForValue) {
          if (sensorDataBuilder_ == null) {
            ensureSensorDataIsMutable();
            sensorData_.add(builderForValue.build());
            onChanged();
          } else {
            sensorDataBuilder_.addMessage(builderForValue.build());
          }
          return this;
        }
        /**
         * <code>repeated .EnvironmentUpdate.SensorData sensor_data = 6;</code>
         */
        public Builder addSensorData(
            int index, EnvironmentMonitoringProtos.EnvironmentUpdate.SensorData.Builder builderForValue) {
          if (sensorDataBuilder_ == null) {
            ensureSensorDataIsMutable();
            sensorData_.add(index, builderForValue.build());
            onChanged();
          } else {
            sensorDataBuilder_.addMessage(index, builderForValue.build());
          }
          return this;
        }
        /**
         * <code>repeated .EnvironmentUpdate.SensorData sensor_data = 6;</code>
         */
        public Builder addAllSensorData(
            java.lang.Iterable<? extends EnvironmentMonitoringProtos.EnvironmentUpdate.SensorData> values) {
          if (sensorDataBuilder_ == null) {
            ensureSensorDataIsMutable();
            com.google.protobuf.AbstractMessageLite.Builder.addAll(
                values, sensorData_);
            onChanged();
          } else {
            sensorDataBuilder_.addAllMessages(values);
          }
          return this;
        }
        /**
         * <code>repeated .EnvironmentUpdate.SensorData sensor_data = 6;</code>
         */
        public Builder clearSensorData() {
          if (sensorDataBuilder_ == null) {
            sensorData_ = java.util.Collections.emptyList();
            bitField0_ = (bitField0_ & ~0x00000020);
            onChanged();
          } else {
            sensorDataBuilder_.clear();
          }
          return this;
        }
        /**
         * <code>repeated .EnvironmentUpdate.SensorData sensor_data = 6;</code>
         */
        public Builder removeSensorData(int index) {
          if (sensorDataBuilder_ == null) {
            ensureSensorDataIsMutable();
            sensorData_.remove(index);
            onChanged();
          } else {
            sensorDataBuilder_.remove(index);
          }
          return this;
        }
        /**
         * <code>repeated .EnvironmentUpdate.SensorData sensor_data = 6;</code>
         */
        public EnvironmentMonitoringProtos.EnvironmentUpdate.SensorData.Builder getSensorDataBuilder(
            int index) {
          return getSensorDataFieldBuilder().getBuilder(index);
        }
        /**
         * <code>repeated .EnvironmentUpdate.SensorData sensor_data = 6;</code>
         */
        public EnvironmentMonitoringProtos.EnvironmentUpdate.SensorDataOrBuilder getSensorDataOrBuilder(
            int index) {
          if (sensorDataBuilder_ == null) {
            return sensorData_.get(index);  } else {
            return sensorDataBuilder_.getMessageOrBuilder(index);
          }
        }
        /**
         * <code>repeated .EnvironmentUpdate.SensorData sensor_data = 6;</code>
         */
        public java.util.List<? extends EnvironmentMonitoringProtos.EnvironmentUpdate.SensorDataOrBuilder> 
             getSensorDataOrBuilderList() {
          if (sensorDataBuilder_ != null) {
            return sensorDataBuilder_.getMessageOrBuilderList();
          } else {
            return java.util.Collections.unmodifiableList(sensorData_);
          }
        }
        /**
         * <code>repeated .EnvironmentUpdate.SensorData sensor_data = 6;</code>
         */
        public EnvironmentMonitoringProtos.EnvironmentUpdate.SensorData.Builder addSensorDataBuilder() {
          return getSensorDataFieldBuilder().addBuilder(
              EnvironmentMonitoringProtos.EnvironmentUpdate.SensorData.getDefaultInstance());
        }
        /**
         * <code>repeated .EnvironmentUpdate.SensorData sensor_data = 6;</code>
         */
        public EnvironmentMonitoringProtos.EnvironmentUpdate.SensorData.Builder addSensorDataBuilder(
            int index) {
          return getSensorDataFieldBuilder().addBuilder(
              index, EnvironmentMonitoringProtos.EnvironmentUpdate.SensorData.getDefaultInstance());
        }
        /**
         * <code>repeated .EnvironmentUpdate.SensorData sensor_data = 6;</code>
         */
        public java.util.List<EnvironmentMonitoringProtos.EnvironmentUpdate.SensorData.Builder> 
             getSensorDataBuilderList() {
          return getSensorDataFieldBuilder().getBuilderList();
        }
        private com.google.protobuf.RepeatedFieldBuilder<
            EnvironmentMonitoringProtos.EnvironmentUpdate.SensorData, EnvironmentMonitoringProtos.EnvironmentUpdate.SensorData.Builder, EnvironmentMonitoringProtos.EnvironmentUpdate.SensorDataOrBuilder> 
            getSensorDataFieldBuilder() {
          if (sensorDataBuilder_ == null) {
            sensorDataBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
                EnvironmentMonitoringProtos.EnvironmentUpdate.SensorData, EnvironmentMonitoringProtos.EnvironmentUpdate.SensorData.Builder, EnvironmentMonitoringProtos.EnvironmentUpdate.SensorDataOrBuilder>(
                    sensorData_,
                    ((bitField0_ & 0x00000020) == 0x00000020),
                    getParentForChildren(),
                    isClean());
            sensorData_ = null;
          }
          return sensorDataBuilder_;
        }

        // @@protoc_insertion_point(builder_scope:EnvironmentUpdate.SensorRecord)
      }

      static {
        defaultInstance = new SensorRecord(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:EnvironmentUpdate.SensorRecord)
    }

    public static final int SENSOR_RECORD_FIELD_NUMBER = 1;
    private java.util.List<EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecord> sensorRecord_;
    /**
     * <code>repeated .EnvironmentUpdate.SensorRecord sensor_record = 1;</code>
     */
    public java.util.List<EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecord> getSensorRecordList() {
      return sensorRecord_;
    }
    /**
     * <code>repeated .EnvironmentUpdate.SensorRecord sensor_record = 1;</code>
     */
    public java.util.List<? extends EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecordOrBuilder> 
        getSensorRecordOrBuilderList() {
      return sensorRecord_;
    }
    /**
     * <code>repeated .EnvironmentUpdate.SensorRecord sensor_record = 1;</code>
     */
    public int getSensorRecordCount() {
      return sensorRecord_.size();
    }
    /**
     * <code>repeated .EnvironmentUpdate.SensorRecord sensor_record = 1;</code>
     */
    public EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecord getSensorRecord(int index) {
      return sensorRecord_.get(index);
    }
    /**
     * <code>repeated .EnvironmentUpdate.SensorRecord sensor_record = 1;</code>
     */
    public EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecordOrBuilder getSensorRecordOrBuilder(
        int index) {
      return sensorRecord_.get(index);
    }

    private void initFields() {
      sensorRecord_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < sensorRecord_.size(); i++) {
        output.writeMessage(1, sensorRecord_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < sensorRecord_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, sensorRecord_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static EnvironmentMonitoringProtos.EnvironmentUpdate parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static EnvironmentMonitoringProtos.EnvironmentUpdate parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static EnvironmentMonitoringProtos.EnvironmentUpdate parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static EnvironmentMonitoringProtos.EnvironmentUpdate parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static EnvironmentMonitoringProtos.EnvironmentUpdate parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static EnvironmentMonitoringProtos.EnvironmentUpdate parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static EnvironmentMonitoringProtos.EnvironmentUpdate parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static EnvironmentMonitoringProtos.EnvironmentUpdate parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static EnvironmentMonitoringProtos.EnvironmentUpdate parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static EnvironmentMonitoringProtos.EnvironmentUpdate parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(EnvironmentMonitoringProtos.EnvironmentUpdate prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code EnvironmentUpdate}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:EnvironmentUpdate)
        EnvironmentMonitoringProtos.EnvironmentUpdateOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return EnvironmentMonitoringProtos.internal_static_EnvironmentUpdate_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return EnvironmentMonitoringProtos.internal_static_EnvironmentUpdate_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                EnvironmentMonitoringProtos.EnvironmentUpdate.class, EnvironmentMonitoringProtos.EnvironmentUpdate.Builder.class);
      }

      // Construct using EnvironmentMonitoringProtos.EnvironmentUpdate.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getSensorRecordFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (sensorRecordBuilder_ == null) {
          sensorRecord_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          sensorRecordBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return EnvironmentMonitoringProtos.internal_static_EnvironmentUpdate_descriptor;
      }

      public EnvironmentMonitoringProtos.EnvironmentUpdate getDefaultInstanceForType() {
        return EnvironmentMonitoringProtos.EnvironmentUpdate.getDefaultInstance();
      }

      public EnvironmentMonitoringProtos.EnvironmentUpdate build() {
        EnvironmentMonitoringProtos.EnvironmentUpdate result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public EnvironmentMonitoringProtos.EnvironmentUpdate buildPartial() {
        EnvironmentMonitoringProtos.EnvironmentUpdate result = new EnvironmentMonitoringProtos.EnvironmentUpdate(this);
        int from_bitField0_ = bitField0_;
        if (sensorRecordBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            sensorRecord_ = java.util.Collections.unmodifiableList(sensorRecord_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.sensorRecord_ = sensorRecord_;
        } else {
          result.sensorRecord_ = sensorRecordBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof EnvironmentMonitoringProtos.EnvironmentUpdate) {
          return mergeFrom((EnvironmentMonitoringProtos.EnvironmentUpdate)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(EnvironmentMonitoringProtos.EnvironmentUpdate other) {
        if (other == EnvironmentMonitoringProtos.EnvironmentUpdate.getDefaultInstance()) return this;
        if (sensorRecordBuilder_ == null) {
          if (!other.sensorRecord_.isEmpty()) {
            if (sensorRecord_.isEmpty()) {
              sensorRecord_ = other.sensorRecord_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureSensorRecordIsMutable();
              sensorRecord_.addAll(other.sensorRecord_);
            }
            onChanged();
          }
        } else {
          if (!other.sensorRecord_.isEmpty()) {
            if (sensorRecordBuilder_.isEmpty()) {
              sensorRecordBuilder_.dispose();
              sensorRecordBuilder_ = null;
              sensorRecord_ = other.sensorRecord_;
              bitField0_ = (bitField0_ & ~0x00000001);
              sensorRecordBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getSensorRecordFieldBuilder() : null;
            } else {
              sensorRecordBuilder_.addAllMessages(other.sensorRecord_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        EnvironmentMonitoringProtos.EnvironmentUpdate parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (EnvironmentMonitoringProtos.EnvironmentUpdate) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecord> sensorRecord_ =
        java.util.Collections.emptyList();
      private void ensureSensorRecordIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          sensorRecord_ = new java.util.ArrayList<EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecord>(sensorRecord_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecord, EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecord.Builder, EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecordOrBuilder> sensorRecordBuilder_;

      /**
       * <code>repeated .EnvironmentUpdate.SensorRecord sensor_record = 1;</code>
       */
      public java.util.List<EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecord> getSensorRecordList() {
        if (sensorRecordBuilder_ == null) {
          return java.util.Collections.unmodifiableList(sensorRecord_);
        } else {
          return sensorRecordBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .EnvironmentUpdate.SensorRecord sensor_record = 1;</code>
       */
      public int getSensorRecordCount() {
        if (sensorRecordBuilder_ == null) {
          return sensorRecord_.size();
        } else {
          return sensorRecordBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .EnvironmentUpdate.SensorRecord sensor_record = 1;</code>
       */
      public EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecord getSensorRecord(int index) {
        if (sensorRecordBuilder_ == null) {
          return sensorRecord_.get(index);
        } else {
          return sensorRecordBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .EnvironmentUpdate.SensorRecord sensor_record = 1;</code>
       */
      public Builder setSensorRecord(
          int index, EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecord value) {
        if (sensorRecordBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSensorRecordIsMutable();
          sensorRecord_.set(index, value);
          onChanged();
        } else {
          sensorRecordBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .EnvironmentUpdate.SensorRecord sensor_record = 1;</code>
       */
      public Builder setSensorRecord(
          int index, EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecord.Builder builderForValue) {
        if (sensorRecordBuilder_ == null) {
          ensureSensorRecordIsMutable();
          sensorRecord_.set(index, builderForValue.build());
          onChanged();
        } else {
          sensorRecordBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .EnvironmentUpdate.SensorRecord sensor_record = 1;</code>
       */
      public Builder addSensorRecord(EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecord value) {
        if (sensorRecordBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSensorRecordIsMutable();
          sensorRecord_.add(value);
          onChanged();
        } else {
          sensorRecordBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .EnvironmentUpdate.SensorRecord sensor_record = 1;</code>
       */
      public Builder addSensorRecord(
          int index, EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecord value) {
        if (sensorRecordBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSensorRecordIsMutable();
          sensorRecord_.add(index, value);
          onChanged();
        } else {
          sensorRecordBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .EnvironmentUpdate.SensorRecord sensor_record = 1;</code>
       */
      public Builder addSensorRecord(
          EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecord.Builder builderForValue) {
        if (sensorRecordBuilder_ == null) {
          ensureSensorRecordIsMutable();
          sensorRecord_.add(builderForValue.build());
          onChanged();
        } else {
          sensorRecordBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .EnvironmentUpdate.SensorRecord sensor_record = 1;</code>
       */
      public Builder addSensorRecord(
          int index, EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecord.Builder builderForValue) {
        if (sensorRecordBuilder_ == null) {
          ensureSensorRecordIsMutable();
          sensorRecord_.add(index, builderForValue.build());
          onChanged();
        } else {
          sensorRecordBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .EnvironmentUpdate.SensorRecord sensor_record = 1;</code>
       */
      public Builder addAllSensorRecord(
          java.lang.Iterable<? extends EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecord> values) {
        if (sensorRecordBuilder_ == null) {
          ensureSensorRecordIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, sensorRecord_);
          onChanged();
        } else {
          sensorRecordBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .EnvironmentUpdate.SensorRecord sensor_record = 1;</code>
       */
      public Builder clearSensorRecord() {
        if (sensorRecordBuilder_ == null) {
          sensorRecord_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          sensorRecordBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .EnvironmentUpdate.SensorRecord sensor_record = 1;</code>
       */
      public Builder removeSensorRecord(int index) {
        if (sensorRecordBuilder_ == null) {
          ensureSensorRecordIsMutable();
          sensorRecord_.remove(index);
          onChanged();
        } else {
          sensorRecordBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .EnvironmentUpdate.SensorRecord sensor_record = 1;</code>
       */
      public EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecord.Builder getSensorRecordBuilder(
          int index) {
        return getSensorRecordFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .EnvironmentUpdate.SensorRecord sensor_record = 1;</code>
       */
      public EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecordOrBuilder getSensorRecordOrBuilder(
          int index) {
        if (sensorRecordBuilder_ == null) {
          return sensorRecord_.get(index);  } else {
          return sensorRecordBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .EnvironmentUpdate.SensorRecord sensor_record = 1;</code>
       */
      public java.util.List<? extends EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecordOrBuilder> 
           getSensorRecordOrBuilderList() {
        if (sensorRecordBuilder_ != null) {
          return sensorRecordBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(sensorRecord_);
        }
      }
      /**
       * <code>repeated .EnvironmentUpdate.SensorRecord sensor_record = 1;</code>
       */
      public EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecord.Builder addSensorRecordBuilder() {
        return getSensorRecordFieldBuilder().addBuilder(
            EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecord.getDefaultInstance());
      }
      /**
       * <code>repeated .EnvironmentUpdate.SensorRecord sensor_record = 1;</code>
       */
      public EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecord.Builder addSensorRecordBuilder(
          int index) {
        return getSensorRecordFieldBuilder().addBuilder(
            index, EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecord.getDefaultInstance());
      }
      /**
       * <code>repeated .EnvironmentUpdate.SensorRecord sensor_record = 1;</code>
       */
      public java.util.List<EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecord.Builder> 
           getSensorRecordBuilderList() {
        return getSensorRecordFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecord, EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecord.Builder, EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecordOrBuilder> 
          getSensorRecordFieldBuilder() {
        if (sensorRecordBuilder_ == null) {
          sensorRecordBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecord, EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecord.Builder, EnvironmentMonitoringProtos.EnvironmentUpdate.SensorRecordOrBuilder>(
                  sensorRecord_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          sensorRecord_ = null;
        }
        return sensorRecordBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:EnvironmentUpdate)
    }

    static {
      defaultInstance = new EnvironmentUpdate(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:EnvironmentUpdate)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EnvironmentUpdate_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_EnvironmentUpdate_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EnvironmentUpdate_SensorData_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_EnvironmentUpdate_SensorData_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EnvironmentUpdate_SensorRecord_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_EnvironmentUpdate_SensorRecord_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tenv.proto\"\233\002\n\021EnvironmentUpdate\0226\n\rsen" +
      "sor_record\030\001 \003(\0132\037.EnvironmentUpdate.Sen" +
      "sorRecord\032(\n\nSensorData\022\013\n\003key\030\001 \001(\005\022\r\n\005" +
      "value\030\002 \001(\002\032\243\001\n\014SensorRecord\022\020\n\010latitude" +
      "\030\001 \001(\001\022\021\n\tlongitude\030\002 \001(\001\022\021\n\ttimestamp\030\003" +
      " \001(\003\022\016\n\006car_id\030\004 \001(\t\022\027\n\017sequence_number\030" +
      "\005 \001(\005\0222\n\013sensor_data\030\006 \003(\0132\035.Environment" +
      "Update.SensorDataB\035B\033EnvironmentMonitori" +
      "ngProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_EnvironmentUpdate_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_EnvironmentUpdate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_EnvironmentUpdate_descriptor,
        new java.lang.String[] { "SensorRecord", });
    internal_static_EnvironmentUpdate_SensorData_descriptor =
      internal_static_EnvironmentUpdate_descriptor.getNestedTypes().get(0);
    internal_static_EnvironmentUpdate_SensorData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_EnvironmentUpdate_SensorData_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_EnvironmentUpdate_SensorRecord_descriptor =
      internal_static_EnvironmentUpdate_descriptor.getNestedTypes().get(1);
    internal_static_EnvironmentUpdate_SensorRecord_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_EnvironmentUpdate_SensorRecord_descriptor,
        new java.lang.String[] { "Latitude", "Longitude", "Timestamp", "CarId", "SequenceNumber", "SensorData", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
